version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: backend_db
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
